### ISSUE TITLE
Does it minify?

### ISSUE THREAD

**Issue by Boscop** [nathan/parcel-redux#28]
Can it minify the js source? Or only bundle?

**Comment by nathan** [comment]
Minifying would take more time, defeating the purpose of this bundler, viz., speed. Parcel(-redux) is a **development** bundler which operates as fast as possible so you can iterate quickly; minification is only useful in production, where you should be using a different bundler anyway.

**Comment by Boscop** [comment]
Thanks. Btw, which bundler would you recommend for production, parcel.js?

**Comment by nathan** [comment]
I don't have a strong preference regarding production bundlers. (Parcel.js is unrelated, Devon Govett just copied the name. I'm not much of a fan of its feature set, but if it you like it then go for it.)

**Comment by bfred-it** [comment]
> in production, where you should be using a different bundler anyway

Should you? What if the production bundler behaves differently?

**Comment by bfred-it** [comment]
> In terms of using Pax in production, you probably don't want to do that

That's the problem, if a slight difference in code execution order appears between two bundlers you're not gonna notice for a long while. Debugging that will be troublesome if your development pipeline is different from production.

**Comment by nathan** [comment]
> a slight difference in code execution order

CJS execution order is entirely deterministic, and ESM execution order is explicitly unspecified. In the former case, a difference is a bundler bug, in the latter case a difference is a bug in your code, which should not rely on a particular execution order.

Feel free to run your tests using your production bundler. Pax is just there to speed up development.

**Comment by joseluisq** [comment]
> Feel free to run your tests using your production bundler if it makes you feel better. Pax is just there to speed up __development__.

I would be good idea to make users notice this via `README.md` file.

**Comment by nathan** [comment]
@joseluisq It's already in the README:

> Use Pax while you’re developing, and iterate to your heart’s content. Use your super-cool, magical, slow-as-molasses bundler for releases, when you don’t care how long it takes to run.

**Comment by joseluisq** [comment]
@nathan awesome!
> @joseluisq It's already in the README:
> 
> Use Pax while you’re developing, and iterate to your heart’s content. Use your super-cool, magical, slow-as-molasses bundler for releases, when you don’t care how long it takes to run.
